sequenceDiagram

participant CLI as Pixie AWS Authenticator
participant B as Web Browser (Pixie hosted)
participant ACE as Access Code Exchanger
participant STS as AWS STS

CLI->>CLI: Generate state, code_verified, code_challenge
CLI->>B: webbrowser.open(https://auth...com/authorize?state=x&code_challenge=x&...)
B->>ACE: GET https://auth...com/authorize?state=x&code_challenge=x&...
Note right of B: User gets authenticated
ACE->>B: GET http://localhost:31338?code=...&state=...

CLI->>ACE: GET https://auth...com/token {code=..., state=...}
ACE->>CLI: JSON {id_token, access_token}

CLI->>STS: GET https://...amazonaws../get-sts?id_token...
STS->>CLI: JSON {access_key_id=..., access_key=...}

