name: Test
on:
  - push
  - pull_request
jobs:
  test-maws:
    name: Test maws
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        exclude:
        - platform: macos-latest
          python-version: "3.7"
        - platform: macos-latest
          python-version: "3.9"
        - platform: macos-latest
          python-version: "3.10"
        - platform: windows-latest
          python-version: "3.7"
        - platform: windows-latest
          python-version: "3.8"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
          pip install -U pip
          pip install tox tox-gh-actions
    - name: Test with tox
      env:
        PLATFORM: ${{ matrix.platform }}
      run: tox
  test-cloud-functions:
    name: Test cloud functions idtoken_for_roles and group_role_map_builder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
          pip install -U pip
          pip install tox tox-gh-actions
    - name: Test with tox
      working-directory: ./cloudformation
      run: tox